name: Release Charts

on:
  push:
    tags: ["**"]

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Get the chart name and version from the tag
        uses: actions/github-script@v6
        id: info
        with:
          script: |
            const tag = process.env.GITHUB_REF_NAME
            const matches = tag.match(/^(.+)-([0-9]+\.[0-9]+\.[0-9]+)$/)
            console.log(matches)
            core.setOutput('name', matches[1])
            core.setOutput('version', matches[2])

      - name: Checkout
        uses: actions/checkout@v3

      - name: Publish Helm chart
        uses: superbrothers/helm-gh-pages@chart_dir
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          chart_dir: charts/${{steps.info.outputs.name}}
          chart_version: ${{steps.info.outputs.version}}
